name: "publish"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: node
<<<<<<< HEAD
        uses: actions/setup-node@2
=======
        uses: actions/setup-node@v2
>>>>>>> chore(release): 0.1.16
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
